server
{
	listen 127.0.0.1:8080
	root /var/www/site1
	client_max_body_size 1000000

	error_pages
		404 /errors/404.html
		413 /errors/413.html

	location
		path /
		methods GET POST
		index index.html
		autoindex false

	location
		path /images
		methods GET
		root /var/www/site1/pictures
		autoindex true

	location
		path /upload
		methods POST

	location
		path /old-page
		return 301 url /new-page

	location
		path /cgi-bin
		root /var/www/site1/cgi-bin
		methods GET POST
		cgi .php /usr/bin/php-cgi
		cgi .py /usr/bin/py-cgi
		cgi .js /usr/bin/js-cgi
}